# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.3
org.gradle.parallel=true
org.gradle.warning.mode=all
# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=0.9.3
maven_group=me.marin
archives_base_name=lockout-fabric
# Dependencies
# check this on https://fabricmc.net/develop
fabric_api_version=0.150.0+26.1.2
